<a href="https://colab.research.google.com/github/WoradeeKongthong/medical_cost_regression/blob/master/03_Medical_Cost_Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
## Data Preprocessing

# importing the dataset
df = pd.read_csv('/content/drive/My Drive/life-long learning/MyProjects/Medical Cost/cleaned_insurance.csv')

In [181]:
df.head()   

age     sex     bmi  ...      charges  bmi_status AgeInterval
0   19  female  27.900  ...  16884.92400  overweight    (15, 25]
1   18    male  33.770  ...   1725.55230     obesity    (15, 25]
2   28    male  33.000  ...   4449.46200     obesity    (25, 45]
3   33    male  22.705  ...  21984.47061       ideal    (25, 45]
4   32    male  28.880  ...   3866.85520  overweight    (25, 45]

[5 rows x 9 columns]

In [0]:
X = df.iloc[:, :6].values
y = df.iloc[:, 6].values

In [183]:
print(X)

[[19 'female' 27.9 0 True 'southwest']
 [18 'male' 33.77 1 False 'southeast']
 [28 'male' 33.0 3 False 'southeast']
 ...
 [18 'female' 36.85 0 False 'southeast']
 [21 'female' 25.8 0 False 'southwest']
 [61 'female' 29.07 0 True 'northwest']]


In [184]:
print(y)

[16884.92  1725.55  4449.46 ...  1629.83  2007.94 29141.36]


In [0]:
# encoding categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(drop='first'), [1,4,5])], remainder='passthrough')
X = ct.fit_transform(X)

In [186]:
print(X[:5])

[[0.0 1.0 0.0 0.0 1.0 19 27.9 0]
 [1.0 0.0 0.0 1.0 0.0 18 33.77 1]
 [1.0 0.0 0.0 1.0 0.0 28 33.0 3]
 [1.0 0.0 1.0 0.0 0.0 33 22.705 0]
 [1.0 0.0 1.0 0.0 0.0 32 28.88 0]]


In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [188]:
# Training the Multiple Linear Regression model on the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [189]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)[:10])

[[ 9919.72 30284.64]
 [ 2244.03  2597.78]
 [ 8214.15 12404.88]
 [37112.67 43921.18]
 [17479.66 12574.05]
 [ 5645.23  4564.19]
 [11629.63 11085.59]
 [11169.12  8964.06]
 [ 5066.26  6272.48]
 [ 1219.35  3378.91]]


In [190]:
# Model Evaluation
from sklearn.metrics import r2_score,explained_variance_score
print(r2_score(y_test, y_pred))
print(explained_variance_score(y_test, y_pred))

0.798390966569285
0.7983944690397611


In [191]:
# Applying K-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = regressor, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 73.16 %
Standard Deviation: 3.58 %
